### ISSUE TITLE
BucketExistsAsync throw exception, if bucket doesn't exist.

### ISSUE THREAD

**Issue by Dudod** [minio/minio-dotnet#397]
I tried to use package 3.1.11 and DotNet Core 3.1.

BucketExistsAsync throw exception Minio.Exceptions.ErrorResponse with message "MinIO API responded with message=The specified bucket does not exist", if bucket doesn't exist.
If bucket exists it returns true.

It works correctly in package 3.0.11

**Comment by AthilTech** [comment]
i have the same Issue with package 3.1.11 and DotNet Core 2.2.

**Comment by AthilTech** [comment]
i have found the solution ,is to get the BucketExistsAsync instruction up to the try catch 
like this : 
 var bucketNameLowerCase = bucketName.ToLower(); 
            bool found = await minio.BucketExistsAsync(bucketNameLowerCase); //change this line up to Try catch
            try
            {
                // Make a bucket on the server, if not already present.
               
                if (!found)
                {
                    
                    await minio.MakeBucketAsync(bucketNameLowerCase);
                }
                // Upload a file to bucket.
                await minio.PutObjectAsync(bucketNameLowerCase, objectName, filePath, contentType);
                Console.WriteLine("Successfully uploaded " + objectName);
            }
            catch (MinioException e)
            {
                Console.WriteLine("File Upload Error: {0}", e.Message);
            }

**Comment by Dudod** [comment]
Yeap) I solved this problem like you) But, I think, it's a bug.

**Comment by poornas** [comment]
thanks @Dudod and @AthilTech , this bug is being fixed in #392

**Comment by yilezhu** [comment]
> thanks @Dudod and @AthilTech , this bug is being fixed in #392

Can you republish a nuget package? At present, this problem still exists in 3.1.11, unless you download the source code directly and add a reference！Thanks and look forward to~

**Comment by poornas** [comment]
3.1.12 is released, closing this issue.

**Comment by Richa-Dits** [comment]
I am not able to create bucket. Can somone tell the reason? What will be wrong.

public async Task Invoke(HttpContext context)
{
    var lists = await _minioClient.ListBucketsAsync();
    // var bucketName = "demo-bucket";

    var bktExistArgs = new BucketExistsArgs().WithBucket(bucketName);
    bool found = await _minioClient.BucketExistsAsync(bktExistArgs);

    if (lists.Buckets == null)
    {
        //Create bucket
        var mkBktArgs = new MakeBucketArgs().WithBucket(bucketName);
        await _minioClient.MakeBucketAsync(mkBktArgs);
        Console.WriteLine(bucketName + "created successfully");
    }
    else
    {
        Console.WriteLine(bucketName + "already exists");
    }
    await UploadFile(_minioClient);
    await _next(context);
}

THis is my code. Bucket is not creating.
